using BankingManagement.Application.Accounts;
using BankingManagement.Application.Accounts.Requests;
using BankingManagement.Application.Cards;
using BankingManagement.Application.Users;
using BankingManagement.Application.Users.Requests;
using BankingManagementOnlineBanking.API.Infrastructure.Auth.JWT;
using BankingManagementOnlineBanking.API.Infrastructure.Resources;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Security.Claims;

namespace BankingManagementOnlineBanking.API.Controllers
{
    [Produces("application/json")]
    [Route("api/[controller]")]
    [Authorize(Roles = "Bronze, Silver, Gold, Platinum")]
    [ApiController]
    public class UserController : ControllerBase
    {
        #region Private Memebers and CTOR

        private readonly IUserService _userService;
        private readonly IAccountService _accountService;
        private readonly ICardService _cardService;
        private readonly IOptions<JWTConfiguration> _jwtConfiguration;
        private readonly int userId;

        public UserController(IUserService userService, IOptions<JWTConfiguration> configuration, IAccountService accountService, ICardService cardService, IHttpContextAccessor contextAccessor)
        {
            _userService = userService;
            _jwtConfiguration = configuration;
            _accountService = accountService;
            _cardService = cardService;

            if (contextAccessor.HttpContext!.User != null && contextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier) != null)
                userId = int.Parse(contextAccessor.HttpContext.User.FindFirst(ClaimTypes.NameIdentifier)!.Value);
        }

        #endregion Private Memebers and CTOR

        /// <summary>
        /// Login for user
        /// </summary>
        /// <returns>JSON Web Token which is generated by server</returns>
        /// <param name="model"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpPost("LogIn")]
        public async Task<ActionResult> LogIn(UserLoginRequestModel model, CancellationToken cancellationToken)
        {
            var user = await _userService.Authenticate(model, cancellationToken);

            return Ok(JWTHelper.GenerateToken(user, _jwtConfiguration));
        }

        /// <summary>
        /// Password change for users
        /// </summary>
        /// <param name="model"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [HttpPut("ChangePassword")]
        public async Task<ActionResult> ChangePassword(UserPasswordChangeModel model, CancellationToken cancellationToken)
        {
            await _userService.ChangePassword(model, userId, cancellationToken);

            return Ok();
        }

        /// <summary>
        /// Returns Accounts of User
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [HttpGet("MyAccounts")]
        public async Task<ActionResult> GetAccounts(CancellationToken cancellationToken)
        {
            var accounts = await _accountService.GetAccounts(userId, cancellationToken);

            return Ok(accounts);
        }

        /// <summary>
        /// Returns Cards of User
        /// </summary>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [HttpGet("MyCards")]
        public async Task<ActionResult> GetCards(CancellationToken cancellationToken)
        {
            var cards = await _cardService.GetCardsAsymc(userId, cancellationToken);

            return Ok(cards);
        }

        /// <summary>
        /// Transfers money from one account to another owner's account
        /// </summary>
        /// <param name="model"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [HttpPut("TransferToMyAccount")]
        public async Task<ActionResult> TransferToOwnAccount(TransferModelRequest model, CancellationToken cancellationToken)
        {
            await _accountService.TransferToOwnAccountAsync(model, userId, cancellationToken);

            return Ok(ResponseTexts.Transaction);
        }

        /// <summary>
        /// Transfers money from one account to another
        /// </summary>
        /// <param name="model"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Route("TransferToAnotherAccount")]
        [HttpPut]
        public async Task<ActionResult> TransferToAnotherAccount(TransferModelRequest model, CancellationToken cancellationToken)
        {
            await _accountService.TransferToOtherAccountAsync(model, userId, cancellationToken);

            return Ok(ResponseTexts.Transaction);
        }

        /// <summary>
        /// Deposit money from here
        /// </summary>
        /// <param name="model"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [HttpPut("Deposit")]
        public async Task<ActionResult> Deposit(AccountDepositRequestModel model, CancellationToken cancellationToken)
        {
            await _accountService.DepositAsync(model, userId, cancellationToken);

            return Ok(ResponseTexts.Deposit);
        }

        /// <summary>
        /// Email confirmation action method
        /// </summary>
        /// <param name="code"></param>
        /// <param name="cancellationToken"></param>
        /// <returns></returns>
        [Route("ConfirmEmail")]
        [AllowAnonymous]
        [HttpGet]
        public async Task<ActionResult> ConfirmEmail(string code, CancellationToken cancellationToken = default)
        {
            await _userService.ConfirmEmailAsync(code, _jwtConfiguration.Value.Secret, cancellationToken);

            return Ok("Email Confirmed");
        }
    }
}