//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingManagement.Application.Infrastructure.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionTexts {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionTexts() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankingManagement.Application.Infrastructure.Resources.ExceptionTexts", typeof(ExceptionTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient balance.
        /// </summary>
        internal static string AccountBalance {
            get {
                return ResourceManager.GetString("AccountBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        internal static string AccountNotFound {
            get {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit card number is required.
        /// </summary>
        internal static string CreditCardNumberRequired {
            get {
                return ResourceManager.GetString("CreditCardNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person must be greater than 18 years old.
        /// </summary>
        internal static string DateOfBirthAge {
            get {
                return ResourceManager.GetString("DateOfBirthAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth is required.
        /// </summary>
        internal static string DateOfBirthRequired {
            get {
                return ResourceManager.GetString("DateOfBirthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposit amount must be greater than 0.
        /// </summary>
        internal static string DepositAmount {
            get {
                return ResourceManager.GetString("DepositAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email address already exists.
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have more than one EUR account while registering user.
        /// </summary>
        internal static string DuplicateEURAccount {
            get {
                return ResourceManager.GetString("DuplicateEURAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have more than one GEL account while registering user.
        /// </summary>
        internal static string DuplicateGELAccount {
            get {
                return ResourceManager.GetString("DuplicateGELAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot have more than one USD account while registering user.
        /// </summary>
        internal static string DuplicateUSDAccount {
            get {
                return ResourceManager.GetString("DuplicateUSDAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is already confirmed.
        /// </summary>
        internal static string EmailAlreadyConfirmed {
            get {
                return ResourceManager.GetString("EmailAlreadyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not in a correct format.
        /// </summary>
        internal static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not confirmed.
        /// </summary>
        internal static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required.
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firstname length must not be more than 40 characters.
        /// </summary>
        internal static string FirstNameLength {
            get {
                return ResourceManager.GetString("FirstNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstName is required.
        /// </summary>
        internal static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN is required.
        /// </summary>
        internal static string IBANNotEmpty {
            get {
                return ResourceManager.GetString("IBANNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only withdraw amount which is divisible by 5.
        /// </summary>
        internal static string InvalidAmountToWithdraw {
            get {
                return ResourceManager.GetString("InvalidAmountToWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email or password is inccorect.
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credit card number.
        /// </summary>
        internal static string InvalidCreditCardNumber {
            get {
                return ResourceManager.GetString("InvalidCreditCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid currency.
        /// </summary>
        internal static string InvalidCurrency {
            get {
                return ResourceManager.GetString("InvalidCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid PIN.
        /// </summary>
        internal static string InvalidPin {
            get {
                return ResourceManager.GetString("InvalidPin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this kind of transaction only for transfering between you and other accounts.
        /// </summary>
        internal static string InvalidTransactionToAnotherAccount {
            get {
                return ResourceManager.GetString("InvalidTransactionToAnotherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use this kind of transaction only for transfering between your accounts.
        /// </summary>
        internal static string InvalidTransactionToOwnAccount {
            get {
                return ResourceManager.GetString("InvalidTransactionToOwnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname length must not be more than 50 characters.
        /// </summary>
        internal static string LastNameLength {
            get {
                return ResourceManager.GetString("LastNameLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lastname is required.
        /// </summary>
        internal static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any cards.
        /// </summary>
        internal static string NoCards {
            get {
                return ResourceManager.GetString("NoCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PIN is required.
        /// </summary>
        internal static string PINRequired {
            get {
                return ResourceManager.GetString("PINRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PINs do not match.
        /// </summary>
        internal static string PINsDoNotMatch {
            get {
                return ResourceManager.GetString("PINsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private number can only contain digits.
        /// </summary>
        internal static string PrivateNumberFormat {
            get {
                return ResourceManager.GetString("PrivateNumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private number must contain exactly 11 digits.
        /// </summary>
        internal static string PrivateNumberLength {
            get {
                return ResourceManager.GetString("PrivateNumberLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private number is required.
        /// </summary>
        internal static string PrivateNumberRequired {
            get {
                return ResourceManager.GetString("PrivateNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction cannot be empty.
        /// </summary>
        internal static string TransactionNull {
            get {
                return ResourceManager.GetString("TransactionNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer amount must be greater than 0.
        /// </summary>
        internal static string TransferAmount {
            get {
                return ResourceManager.GetString("TransferAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot withdraw more than 10000 in one day.
        /// </summary>
        internal static string WithdrawLimit {
            get {
                return ResourceManager.GetString("WithdrawLimit", resourceCulture);
            }
        }
    }
}
